environments:
  default:
    connections:
      google_cloud_platform:
        - name: gcp-default
          service_account_file: ./terraform/gcp-key.json
          project_id: suara-pipeline
          location: asia-southeast1