services:
  suara-worker:
    build:
      context: ..         
      dockerfile: docker/Dockerfile  
    container_name: suara_worker
    env_file:
      - ../.env           
    volumes:
      - ..:/app          
      - ../terraform/gcp-key.json:/app/gcp-key.json:ro