services:
  bruin-worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: suara-worker
    volumes:
      - ..:/app
      - ~/.config/gcloud:/root/.config/gcloud # Optional: shares your gcloud auth
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/terraform/gcp-key.json
    network_mode: host